# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9e882bf949db432aee67ba232592083cdff3ab8e2f6978880939eb554569513579f8429a25d6c4fd3eb8c08ea785d587632d2bd5aef0b657f58ac98652f12026

test:
  secret_key_base: 54c9e33c24f15a377d4595cb71477224e71709e8dd52c828359c8ebec7ed8acbda4697ece86b3e1d53192361bb4624bf35d65a934b3aecd9fa72804d16053281

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
